import {
  BarChart3,
  BedDouble,
  Bell,
  Building2,
  CalendarClock,
  CalendarDays,
  CalendarOff,
  ClipboardList,
  FlaskConical,
  ArrowRightLeft,
  KeyRound,
  Landmark,
  LayoutDashboard,
  Pill,
  Receipt,
  Scan,
  Settings,
  ShieldCheck,
  ShoppingCart,
  Siren,
  Stethoscope,
  Syringe,
  TrendingDown,
  UserCog,
  Users,
  Video,
  Wallet,
  Wrench,
} from "lucide-react";
import type { NavSection } from "@/components/layout/sidebar";

export const navigationSections: NavSection[] = [
  {
    title: "Clinique",
    items: [
      { label: "Tableau de bord", href: "/dashboard", icon: LayoutDashboard },
      { label: "Patients", href: "/patients", icon: Users },
      { label: "Rendez-vous", href: "/rendez-vous", icon: CalendarDays },
      { label: "Téléconsultation", href: "/teleconsultations", icon: Video },
      { label: "Référencement", href: "/referencement", icon: ArrowRightLeft },
      { label: "Consultations", href: "/consultations", icon: Stethoscope },
      { label: "Laboratoire", href: "/laboratoire", icon: FlaskConical },
      { label: "Imagerie", href: "/imagerie", icon: Scan },
      { label: "Hospitalisation", href: "/hospitalisation", icon: BedDouble },
      { label: "Bloc opératoire", href: "/bloc-operatoire", icon: Syringe },
    ],
  },
  {
    title: "Logistique",
    items: [
      { label: "Pharmacie", href: "/pharmacie", icon: Pill },
      { label: "Achats", href: "/achats", icon: ShoppingCart },
      { label: "Équipements biomédicaux", href: "/equipements", icon: Wrench },
    ],
  },
  {
    title: "Administration",
    items: [
      { label: "Facturation", href: "/facturation", icon: Receipt },
      { label: "Caisse", href: "/caisse", icon: Wallet },
      { label: "Assurances / IPM", href: "/assurances", icon: Landmark },
      { label: "Créances", href: "/creances", icon: TrendingDown },
      { label: "Personnel", href: "/personnel", icon: UserCog },
      { label: "Comptes utilisateurs", href: "/comptes-utilisateurs", icon: KeyRound },
      { label: "Prescripteurs externes", href: "/prescripteurs-externes", icon: Stethoscope },
      { label: "Plannings", href: "/plannings", icon: CalendarClock },
      { label: "Congés", href: "/conges", icon: CalendarOff },
      { label: "Gardes / astreintes", href: "/gardes-astreintes", icon: Siren },
      { label: "Qualité & Réclamations", href: "/qualite", icon: ClipboardList },
      { label: "Structures & sites", href: "/structures", icon: Building2 },
      { label: "Templates de notification", href: "/templates-notification", icon: Bell },
    ],
  },
  {
    title: "Pilotage",
    items: [
      { label: "Rapports", href: "/rapports", icon: BarChart3 },
      { label: "Audit", href: "/audit", icon: ShieldCheck },
      { label: "Paramètres", href: "/parametres", icon: Settings },
    ],
  },
];
