const ROLE_LABELS: Record<string, string> = {
  medecin: "Médecin",
  infirmier: "Infirmier",
  secretaire: "Secrétaire",
  administrateur: "Administrateur",
  direction: "Direction",
  directeur_medical: "Directeur médical",
  comptable: "Comptable",
  caissier: "Caissier",
  conformite: "Conformité",
  rh: "Ressources humaines",
  manager: "Manager",
  gestionnaire_stock: "Gestionnaire de stock",
  biomedical: "Biomédical",
  pharmacien: "Pharmacien",
  achats: "Achats",
  biologiste: "Biologiste",
  technicien_laboratoire: "Technicien de laboratoire",
  radiologue: "Radiologue",
  manipulateur_radio: "Manipulateur radio",
  chirurgien: "Chirurgien",
  anesthesiste: "Anesthésiste",
  sage_femme: "Sage-femme",
  gynecologue: "Gynécologue",
  dentiste: "Dentiste",
  nephrologue: "Néphrologue",
  infirmier_dialyse: "Infirmier de dialyse",
  ophtalmologue: "Ophtalmologue",
  cardiologue: "Cardiologue",
  kinesitherapeute: "Kinésithérapeute",
  oncologue: "Oncologue",
  specialiste_pma: "Spécialiste PMA",
  psychiatre: "Psychiatre",
  psychologue: "Psychologue",
  pediatre: "Pédiatre",
  medecin_travail: "Médecin du travail",
  infirmier_domicile: "Infirmier à domicile",
};

export function roleLabel(role: string | undefined): string {
  if (!role) return "—";
  return ROLE_LABELS[role] ?? role;
}
